language: node_js
env: 
  - NPMREGISTRYURL=
  - NPMREGISTRYURL=http://52.202.166.115
  - NPMREGISTRYURL=http://52.202.196.38
node_js:
  - node_js: '6'
  - node_js: '5'
  - node_js: '4'
  - node_js: '0.12'
  - node_js: '0.10'
before_install:
  - echo registry=$NPMREGISTRYURL >> .npmrc
  - 'npm install -g npm@latest'
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && tap --coverage-report=text-lcov | ./node_modules/.bin/coveralls'
